<a href="https://colab.research.google.com/github/rakeshp1/data690_rakesh/blob/main/Assignment_08/Inclass_practice_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In class Session 8
- Name: Rakesh
- Date: 10/21/21

In [79]:
import pandas as pd
import plotly.express as px

In [80]:
df = pd.read_csv("/content/wdi_data.csv")
df.sample(10)

      Unnamed: 0  Year  ...         Income Group    Lending Type
3130        3130  2018  ...  Lower middle income             IDA
2919        2919  2017  ...          High income  Not classified
3763        3763  2019  ...          High income  Not classified
3848        3848  2019  ...  Upper middle income            IBRD
3545        3545  2016  ...  Upper middle income            IBRD
4162        4162  2018  ...          High income  Not classified
2761        2761  2015  ...          High income  Not classified
2768        2768  2016  ...  Upper middle income             IDA
1169        1169  2019  ...          High income            IBRD
410          410  2017  ...  Upper middle income            IBRD

[10 rows x 9 columns]

In [81]:
df_2019 = df.query("Year == 2019")
df.sample(10)

      Unnamed: 0  Year  ...         Income Group    Lending Type
2439        2439  2017  ...  Upper middle income  Not classified
11            11  2020  ...  Upper middle income            IBRD
710          710  2015  ...  Lower middle income             IDA
1187        1187  2017  ...          High income  Not classified
3180        3180  2020  ...          High income  Not classified
2053        2053  2015  ...  Lower middle income            IBRD
2099        2099  2016  ...  Lower middle income           Blend
3995        3995  2016  ...  Upper middle income            IBRD
1601        1601  2015  ...  Upper middle income            IBRD
1667        1667  2016  ...           Low income             IDA

[10 rows x 9 columns]

In [82]:
df_2019 = df_2019.query("indicator in['SP.DYN.LE00.IN','NY.GDP.PCAP.PP.CD','SP.POP.TOTL'] ")

df_2019

      Unnamed: 0  Year  ...         Income Group    Lending Type
4              4  2019  ...           Low income             IDA
10            10  2019  ...  Upper middle income            IBRD
16            16  2019  ...  Lower middle income            IBRD
22            22  2019  ...  Lower middle income            IBRD
28            28  2019  ...          High income            IBRD
...          ...   ...  ...                  ...             ...
3413        3413  2019  ...          High income  Not classified
3419        3419  2019  ...  Lower middle income  Not classified
3425        3425  2019  ...           Low income             IDA
3431        3431  2019  ...  Lower middle income             IDA
3437        3437  2019  ...  Lower middle income           Blend

[606 rows x 9 columns]

In [83]:
df_2019.drop(columns=["Unnamed: 0", "Year"], inplace=True)

In [84]:
df_2019.head()

           value          indicator  ...         Income Group Lending Type
4    2152.366489  NY.GDP.PCAP.PP.CD  ...           Low income          IDA
10  14230.989507  NY.GDP.PCAP.PP.CD  ...  Upper middle income         IBRD
16  11997.337834  NY.GDP.PCAP.PP.CD  ...  Lower middle income         IBRD
22   6952.419362  NY.GDP.PCAP.PP.CD  ...  Lower middle income         IBRD
28  22460.019253  NY.GDP.PCAP.PP.CD  ...          High income         IBRD

[5 rows x 7 columns]

In [85]:
df_pivot = df_2019.pivot(index=['Country Code','Country Name','Region','Income Group','Lending Type'],columns= 'indicator',values= 'value').reset_index()
df_pivot.head(5)

indicator Country Code Country Name  ... SP.DYN.LE00.IN SP.POP.TOTL
0                  ABW        Aruba  ...         76.293    106310.0
1                  AFG  Afghanistan  ...         64.833  38041757.0
2                  AGO       Angola  ...         61.147  31825299.0
3                  ALB      Albania  ...         78.573   2854191.0
4                  AND      Andorra  ...            NaN     77146.0

[5 rows x 8 columns]

In [87]:
fig = px.scatter(
      df_pivot.dropna(),
      x = "NY.GDP.PCAP.PP.CD",
      y = "SP.DYN.LE00.IN",
      title = "Health vs Wealth",
      labels={"SP.DYN.LE00.IN":"Life expectancy", "NY.GDP.PCAP.PP.CD":"GDP per capita"},
      color="Region",
      hover_name="Country Name",
      text="Country Name",


)

fig.update_traces(textposition='top center')

fig.show()